"""
Unified Menu Factory System for YABOT
Manages role-based menu generation with consistency across the entire system.
"""

import sys
from typing import Dict, List, Any, Optional, Union, Tuple
from enum import Enum
from dataclasses import dataclass, field
from abc import ABC, abstractmethod
import logging
import json
import hashlib
import asyncio
from datetime import datetime

# Import Lucien voice generation system for sophisticated interface personality
from src.ui.lucien_voice_generator import (
    LucienVoiceProfile,
    generate_lucien_response,
    RelationshipLevel,
    LucienPersonalityConstants
)

# Import centralized menu configuration
from src.ui.menu_config import (
    MenuType,
    ActionType,
    UserRole,
    MenuItemConfig,
    MenuConfig,
    menu_system_config
)

# Import UserService for delegation of complex operations
from src.services.user import UserService

logger = logging.getLogger(__name__)

# Telegram Bot API constants
TELEGRAM_CALLBACK_DATA_MAX_LENGTH = 64
TELEGRAM_MAX_INLINE_BUTTONS_PER_ROW = 8
TELEGRAM_MAX_INLINE_KEYBOARD_ROWS = 100


class MenuError(Exception):
    """Base exception for menu-related errors."""
    pass


class CallbackDataTooLongError(MenuError):
    """Raised when callback data exceeds Telegram's limit."""
    pass


class MenuGenerationError(MenuError):
    """Raised when menu generation fails."""
    pass


class ValidationError(MenuError):
    """Raised when menu validation fails."""
    pass


@dataclass
class MenuItem:
    """Represents a single menu item with all necessary properties."""
    id: str
    text: str
    action_type: ActionType
    action_data: str
    icon: str = "📋"
    description: str = ""
    required_role: UserRole = UserRole.FREE_USER
    required_vip: bool = False
    required_level: int = 0
    requires_besitos: int = 0
    visible_condition: Optional[str] = None
    enabled_condition: Optional[str] = None
    submenu_items: List['MenuItem'] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    lucien_voice_text: Optional[str] = None
    required_worthiness: float = 0.0  # Lucien's evaluation score

    def __post_init__(self) -> None:
        """Validate menu item after initialization."""
        self._validate_callback_data()
        self._add_role_indicators()
        self._set_lucien_voice_text()

    @classmethod
    def from_config(cls, config: MenuItemConfig) -> 'MenuItem':
        """Create MenuItem from MenuItemConfig."""
        return cls(
            id=config.id,
            text=config.text,
            action_type=config.action_type,
            action_data=config.action_data,
            icon=config.icon,
            description=config.description,
            required_role=config.required_role,
            required_vip=config.required_vip,
            required_level=config.required_level,
            requires_besitos=config.requires_besitos,
            visible_condition=config.visible_condition,
            enabled_condition=config.enabled_condition,
            metadata=config.metadata,
            required_worthiness=config.required_worthiness
        )

    def _set_lucien_voice_text(self) -> None:
        """Set Lucien voice text if not provided."""
        if self.lucien_voice_text is None:
            # For now, we'll just use the regular text as a fallback
            # In a full implementation, this would be generated by Lucien's voice generator
            self.lucien_voice_text = self.text

    def _validate_callback_data(self) -> None:
        """Validate that callback data doesn't exceed Telegram's limit."""
        if len(self.action_data.encode('utf-8')) > TELEGRAM_CALLBACK_DATA_MAX_LENGTH:
            # Try to compress the callback data
            compressed_data = self._compress_callback_data(self.action_data)
            if len(compressed_data.encode('utf-8')) > TELEGRAM_CALLBACK_DATA_MAX_LENGTH:
                logger.error(
                    f"Callback data too long for item '{self.id}': {len(self.action_data)} bytes, "
                    f"compressed: {len(compressed_data)} bytes"
                )
                raise CallbackDataTooLongError(
                    f"Callback data for '{self.id}' exceeds {TELEGRAM_CALLBACK_DATA_MAX_LENGTH} bytes"
                )
            else:
                logger.warning(
                    f"Compressed callback data for item '{self.id}': {len(self.action_data)} -> {len(compressed_data)} bytes"
                )
                self.action_data = compressed_data

    def _compress_callback_data(self, data: str) -> str:
        """Compress callback data using a mapping strategy."""
        # Create a hash-based mapping for long action data
        if len(data) > TELEGRAM_CALLBACK_DATA_MAX_LENGTH - 10:  # Leave room for prefix
            data_hash = hashlib.md5(data.encode()).hexdigest()[:8]
            return f"hash:{data_hash}"
        return data

    def _add_role_indicators(self) -> None:
        """Add visual indicators for role requirements."""
        indicators = []

        if self.required_vip:
            indicators.append("💎")

        if self.required_level > 0:
            indicators.append(f"Lv.{self.required_level}")

        if self.requires_besitos > 0:
            indicators.append(f"💰{self.requires_besitos}")

        if self.required_role not in [UserRole.FREE_USER, UserRole.GUEST]:
            role_symbols = {
                UserRole.VIP_USER: "⭐",
                UserRole.ADMIN: "🔧",
                UserRole.SUPER_ADMIN: "👑"
            }
            if self.required_role in role_symbols:
                indicators.append(role_symbols[self.required_role])

        if indicators:
            # Add indicators to the end of the text if not already present
            indicator_text = " ".join(indicators)
            if not any(indicator in self.text for indicator in indicators):
                self.text = f"{self.text} {indicator_text}"
                # Also update the lucien_voice_text if it's using the default text
                if self.lucien_voice_text == self.text or self.lucien_voice_text is None:
                    self.lucien_voice_text = self.text


@dataclass
class Menu:
    """Represents a complete menu with header, items, and context."""
    menu_id: str
    title: str
    description: str
    menu_type: MenuType
    required_role: UserRole
    items: List[MenuItem] = field(default_factory=list)
    header_text: str = ""
    footer_text: str = ""
    max_columns: int = 2
    is_dynamic: bool = False
    context_data: Dict[str, Any] = field(default_factory=dict)
    parent_menu_id: Optional[str] = None
    navigation_path: List[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Validate menu after initialization."""
        self._validate_menu()
        self._add_navigation_items()

    @classmethod
    def from_config(cls, config: MenuConfig, user_context: Dict[str, Any] = None) -> 'Menu':
        """Create Menu from MenuConfig."""
        # Convert MenuItemConfig items to MenuItem objects
        menu_items = [MenuItem.from_config(item_config) for item_config in config.items]
        
        return cls(
            menu_id=config.menu_id,
            title=config.title,
            description=config.description,
            menu_type=config.menu_type,
            required_role=config.required_role,
            items=menu_items,
            header_text=config.header_text,
            footer_text=config.footer_text,
            max_columns=config.max_columns,
            is_dynamic=config.is_dynamic,
            parent_menu_id=config.parent_menu_id,
            navigation_path=config.navigation_path
        )

    def _validate_menu(self) -> None:
        """Validate menu structure and constraints."""
        # Validate total number of items
        if len(self.items) > TELEGRAM_MAX_INLINE_KEYBOARD_ROWS * TELEGRAM_MAX_INLINE_BUTTONS_PER_ROW:
            logger.warning(f"Menu '{self.menu_id}' has too many items: {len(self.items)}")

        # Validate menu hierarchy depth
        if len(self.navigation_path) > 5:  # Max 5 levels deep
            logger.warning(f"Menu '{self.menu_id}' is too deep in hierarchy: {len(self.navigation_path)} levels")

    def _add_navigation_items(self) -> None:
        """Add enhanced navigation items with smart breadcrumb functionality."""
        navigation_items = []

        # Create breadcrumb if we have navigation history
        breadcrumb_text = self._generate_breadcrumb()

        # Add back button with context if we have a parent or navigation path
        if self.parent_menu_id or self.navigation_path:
            back_target = self.parent_menu_id or (self.navigation_path[-1] if self.navigation_path else "main_menu")
            back_text = f"◀️ {breadcrumb_text}" if breadcrumb_text else "◀️ Atrás"
            navigation_items.append(MenuItem(
                id="nav_back",
                text=back_text,
                action_type=ActionType.CALLBACK,
                action_data=f"menu:{back_target}",
                description="Volver al menú anterior",
                icon="◀️",
                metadata={"is_navigation": True, "priority": 1000}
            ))

        # Add home button if we're not already in main menu
        if self.menu_id != "main_menu":
            navigation_items.append(MenuItem(
                id="nav_home",
                text="🏠 Inicio",
                action_type=ActionType.CALLBACK,
                action_data="menu:main_menu",
                description="Ir al menú principal",
                icon="🏠",
                metadata={"is_navigation": True, "priority": 999}
            ))

        # Add navigation items to the menu (at the end)
        self.items.extend(navigation_items)

    def _generate_breadcrumb(self) -> str:
        """Generate compact breadcrumb for navigation context."""
        if not self.navigation_path:
            return ""

        # Map menu IDs to short names
        menu_names = {
            "main_menu": "Inicio",
            "narrative_menu": "Historia",
            "experiences_menu": "Experiencias",
            "organic_store_menu": "Tesoros",
            "personal_universe_menu": "Mi Universo",
            "divan_menu": "Diván",
            "admin_menu": "Admin"
        }

        # Get the last menu in path for context
        if self.navigation_path:
            last_menu = self.navigation_path[-1]
            return menu_names.get(last_menu, "Menú")

        return ""


class MenuBuilder(ABC):
    """Abstract base class for menu builders."""

    @abstractmethod
    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build menu for specific user context."""
        pass

    def _log_menu_creation(self, menu_type: str, user_id: str, success: bool,
                          error: Optional[str] = None) -> None:
        """Log menu creation attempts for debugging."""
        timestamp = datetime.now().isoformat()
        if success:
            logger.info(f"[{timestamp}] Menu created successfully: {menu_type} for user {user_id}")
        else:
            logger.error(f"[{timestamp}] Menu creation failed: {menu_type} for user {user_id}. Error: {error}")

    def _validate_user_context(self, user_context: Dict[str, Any]) -> Dict[str, Any]:
        """Validate and normalize user context."""
        required_fields = ['role', 'user_id']
        for field in required_fields:
            if field not in user_context:
                logger.warning(f"Missing required field '{field}' in user context")
                if field == 'role':
                    user_context[field] = 'free_user'
                elif field == 'user_id':
                    user_context[field] = 'unknown'

        # Ensure role is valid
        try:
            UserRole(user_context['role'])
        except ValueError:
            logger.warning(f"Invalid role '{user_context['role']}', defaulting to free_user")
            user_context['role'] = 'free_user'

        return user_context


class MainMenuBuilder(MenuBuilder):
    """Builder for organic unified menu system that shows all options with elegant restrictions."""

    def __init__(self, user_service: Optional[UserService] = None):
        """Initialize MainMenuBuilder with Lucien voice profile.
        
        Args:
            user_service (Optional[UserService]): UserService instance for delegation of complex operations
        """
        self.lucien_profile = LucienVoiceProfile()
        self.user_service = user_service

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build organic main menu that shows all options with elegant restrictions."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            user_role = UserRole(user_context.get('role', 'free_user'))
            has_vip = user_context.get('has_vip', False)
            narrative_level = user_context.get('narrative_level', 1)
            worthiness_score = user_context.get('worthiness_score', 0.0)
            besitos_balance = user_context.get('besitos_balance', 100)

            logger.info(f"Building organic menu for user {user_id} (role: {user_role.value}, vip: {has_vip}, level: {narrative_level})")

            self._adapt_lucien_voice_to_user(user_context)

            # Core navigation items - always visible (matching user configuration)
            items = [
                # Historia, Mochila, Misiones (first row as per config)
                MenuItem(
                    id="historia", text="📖 Historia", action_type=ActionType.SUBMENU,
                    action_data="narrative_menu", description="Tu narrativa personal en evolución",
                    required_role=UserRole.FREE_USER, icon="📖",
                    metadata={"navigation_priority": 100, "category": "main_content"}
                ),
                MenuItem(
                    id="mochila", text="🎒 Mochila", action_type=ActionType.SUBMENU,
                    action_data="mochila_menu", description="Tu inventario y progreso personal",
                    required_role=UserRole.FREE_USER, icon="🎒",
                    metadata={"navigation_priority": 95, "category": "main_content"}
                ),
                MenuItem(
                    id="misiones", text="🎯 Misiones", action_type=ActionType.SUBMENU,
                    action_data="misiones_menu", description="Completa misiones para ganar recompensas",
                    required_role=UserRole.FREE_USER, icon="🎯",
                    metadata={"navigation_priority": 90, "category": "main_content"}
                ),

                # Tienda (second row as per config)
                MenuItem(
                    id="tienda", text="🏪 Tienda", action_type=ActionType.SUBMENU,
                    action_data="tienda_menu", description="Adquiere tesoros con tus besitos",
                    required_role=UserRole.FREE_USER, icon="🏪",
                    metadata={"navigation_priority": 85, "category": "main_content"}
                ),

                # Regalo diario (third row as per config)
                MenuItem(
                    id="regalo_diario", text="🎁 Regalo Diario", action_type=ActionType.CALLBACK,
                    action_data="daily_gift_menu", description="Reclama tu regalo diario",
                    required_role=UserRole.FREE_USER, icon="🎁",
                    metadata={"navigation_priority": 80, "category": "main_content"}
                )
            ]

            # VIP content (Mi Perfil, Recompensas, Ranking, Subastas as per config)
            if has_vip:
                vip_items = [
                    MenuItem(
                        id="mi_perfil", text="👤 Mi Perfil", action_type=ActionType.SUBMENU,
                        action_data="profile_menu", description="Tu perfil VIP y estadísticas",
                        required_role=UserRole.FREE_USER, required_vip=True, icon="👤",
                        metadata={"navigation_priority": 75, "category": "vip_content"}
                    ),
                    MenuItem(
                        id="recompensas", text="🏆 Recompensas", action_type=ActionType.SUBMENU,
                        action_data="rewards_menu", description="Recompensas VIP exclusivas",
                        required_role=UserRole.FREE_USER, required_vip=True, icon="🏆",
                        metadata={"navigation_priority": 70, "category": "vip_content"}
                    ),
                    MenuItem(
                        id="ranking", text="📊 Ranking", action_type=ActionType.SUBMENU,
                        action_data="ranking_menu", description="Compite con otros usuarios VIP",
                        required_role=UserRole.FREE_USER, required_vip=True, icon="📊",
                        metadata={"navigation_priority": 65, "category": "vip_content"}
                    ),
                    MenuItem(
                        id="subastas", text="💎 Subastas", action_type=ActionType.SUBMENU,
                        action_data="auctions_menu", description="Participa en subastas exclusivas",
                        required_role=UserRole.FREE_USER, required_vip=True, icon="💎",
                        metadata={"navigation_priority": 60, "category": "vip_content"}
                    )
                ]
                items.extend(vip_items)
            else:
                # Show VIP options but locked for non-VIP users
                vip_preview_items = [
                    MenuItem(
                        id="vip_preview", text="🌟 Área VIP", action_type=ActionType.CALLBACK,
                        action_data="show_vip_benefits", description="Descubre los beneficios VIP",
                        required_role=UserRole.FREE_USER, icon="🌟",
                        metadata={"navigation_priority": 60, "category": "vip_preview"}
                    )
                ]
                items.extend(vip_preview_items)

            # Add El Diván with organic worthiness explanation if not accessible
            divan_item = await self._create_divan_menu_item(user_context)
            items.append(divan_item)

            # Add admin panel for admins
            if user_role in [UserRole.ADMIN, UserRole.SUPER_ADMIN]:
                items.append(MenuItem(
                    id="admin_panel", text="⚙️ Panel Admin", action_type=ActionType.SUBMENU,
                    action_data="admin_menu", description="Herramientas administrativas",
                    required_role=UserRole.ADMIN, icon="⚙️",
                    metadata={"navigation_priority": 10, "category": "admin"}
                ))

            # Process items with Lucien voice enhancements
            processed_items = []
            for item in items:
                item.lucien_voice_text = self._generate_lucien_menu_text(
                    item.id, item.description, user_context
                )
                processed_items.append(item)

            lucien_header = self._generate_lucien_welcome_message(user_context)
            lucien_footer = self._generate_lucien_footer_message(user_context)

            menu = Menu(
                menu_id="main_menu", title="🏠 Tu Mundo con Diana",
                description="Un universo de posibilidades esperándote",
                menu_type=MenuType.MAIN, required_role=UserRole.FREE_USER, items=processed_items,
                header_text=lucien_header, footer_text=lucien_footer, navigation_path=[]
            )

            self._log_menu_creation("main_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("main_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build main menu: {str(e)}")

    def build_organic_store_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build unified store menu showing all items with elegant restrictions."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            has_vip = user_context.get('has_vip', False)
            narrative_level = user_context.get('narrative_level', 1)
            worthiness_score = user_context.get('worthiness_score', 0.0)
            besitos_balance = user_context.get('besitos_balance', 100)

            items = [
                # Fragmentos Narrativos - Tier system
                MenuItem(
                    id="fragmentos_basicos", text="<b>📚 Fragmentos de Memoria</b>", action_type=ActionType.CALLBACK,
                    action_data="show_narrative_fragments", description="Momentos especiales revividos",
                    required_role=UserRole.FREE_USER, requires_besitos=50
                ),
                MenuItem(
                    id="fragmentos_premium", text="<b>📚 Fragmentos Íntimos</b> ✨", action_type=ActionType.CALLBACK,
                    action_data=self._create_worthiness_check("premium_fragments", worthiness_score, 0.4),
                    description="Recuerdos de profundidad excepcional",
                    required_role=UserRole.FREE_USER, requires_besitos=150, required_worthiness=0.4
                ),

                # Joyas Emocionales - Progressive access
                MenuItem(
                    id="joyas_exploracion", text="<b>💎 Joyas de Exploración</b>", action_type=ActionType.CALLBACK,
                    action_data="show_exploration_gems", description="Potenciadores de conexión emocional",
                    required_role=UserRole.FREE_USER, requires_besitos=80
                ),
                MenuItem(
                    id="joyas_intimidad", text="<b>💎 Joyas de Intimidad</b> ✨", action_type=ActionType.CALLBACK,
                    action_data=self._create_worthiness_check("intimacy_gems", worthiness_score, 0.6),
                    description="Catalizadores de profundidad emocional suprema",
                    required_role=UserRole.FREE_USER, requires_besitos=300, required_worthiness=0.6
                ),

                # Máscaras de Personalidad
                MenuItem(
                    id="mascaras_expresion", text="<b>🎭 Máscaras de Expresión</b>", action_type=ActionType.CALLBACK,
                    action_data="show_expression_masks", description="Nuevas formas de comunicarte con Diana",
                    required_role=UserRole.FREE_USER, requires_besitos=120
                ),

                # Círculo Íntimo - VIP section with elegant presentation
                MenuItem(
                    id="circulo_intimo", text="<b>✨ Círculo Íntimo</b> 💫", action_type=ActionType.SUBMENU,
                    action_data=self._create_vip_access_check("circulo_intimo", has_vip, worthiness_score),
                    description="Experiencias reservadas para los más sofisticados",
                    required_role=UserRole.FREE_USER, required_worthiness=0.7
                )
            ]

            # Process each item with appropriate restrictions and Lucien voice
            processed_items = []
            for item in items:
                processed_item = self._process_store_item(item, user_context)
                processed_items.append(processed_item)

            lucien_header = self._generate_store_header(user_context)
            lucien_footer = self._generate_store_footer(user_context)

            menu = Menu(
                menu_id="organic_store_menu", title="🏪 Colección de Tesoros",
                description="Cada objeto cuenta una historia, cada adquisición revela carácter",
                menu_type=MenuType.STORE, required_role=UserRole.FREE_USER, items=processed_items,
                header_text=lucien_header, footer_text=lucien_footer,
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("organic_store_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("organic_store_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build organic store menu: {str(e)}")

    async def _create_divan_menu_item(self, user_context: Dict[str, Any]) -> MenuItem:
        """Create El Diván menu item with organic access explanation."""
        has_vip = user_context.get('has_vip', False)
        worthiness_score = user_context.get('worthiness_score', 0.0)
        narrative_level = user_context.get('narrative_level', 1)

        if has_vip and narrative_level >= 4 and worthiness_score >= 0.6:
            # Full access
            return MenuItem(
                id="el_divan_acceso", text="🛋️ El Diván", action_type=ActionType.SUBMENU,
                action_data="divan_menu", description="Tu espacio íntimo de comprensión profunda",
                required_role=UserRole.FREE_USER, icon="🛋️",
                metadata={"navigation_priority": 60, "category": "vip_content", "access_status": "granted"}
            )
        else:
            # Visible but with Lucien's elegant explanation
            worthiness_explanation = await self._generate_worthiness_explanation(user_context)
            return MenuItem(
                id="el_divan_evaluacion", text="🛋️ El Diván ✨", action_type=ActionType.CALLBACK,
                action_data="explain_divan_worthiness",
                description="Un privilegio que se gana a través del desarrollo personal",
                required_role=UserRole.FREE_USER, icon="🛋️",
                lucien_voice_text=worthiness_explanation,
                metadata={"navigation_priority": 60, "category": "vip_content", "access_status": "restricted"}
            )

    def _create_worthiness_check(self, item_id: str, current_worthiness: float, required_worthiness: float) -> str:
        """Create action data for worthiness-gated items."""
        if current_worthiness >= required_worthiness:
            return f"access_granted:{item_id}"
        else:
            return f"worthiness_explanation:{item_id}:{required_worthiness}"

    def _create_vip_access_check(self, item_id: str, has_vip: bool, worthiness_score: float) -> str:
        """Create action data for VIP-gated items."""
        if has_vip and worthiness_score >= 0.5:
            return f"vip_access:{item_id}"
        else:
            return f"vip_invitation:{item_id}"

    def _process_store_item(self, item: MenuItem, user_context: Dict[str, Any]) -> MenuItem:
        """Process store item to add appropriate access logic and Lucien voice."""
        has_vip = user_context.get('has_vip', False)
        worthiness_score = user_context.get('worthiness_score', 0.0)
        besitos_balance = user_context.get('besitos_balance', 100)

        # Check if user meets requirements
        can_access = True
        restriction_reason = None

        if item.required_worthiness > worthiness_score:
            can_access = False
            restriction_reason = "worthiness"
        elif item.requires_besitos > besitos_balance:
            can_access = False
            restriction_reason = "besitos"
        elif item.required_vip and not has_vip:
            can_access = False
            restriction_reason = "vip_membership"

        if not can_access:
            # Modify item to show restriction elegantly
            item.lucien_voice_text = self._generate_restriction_explanation(
                item.id, restriction_reason, user_context
            )
            # Change action to explanation instead of purchase
            item.action_data = f"explain_restriction:{item.id}:{restriction_reason}"
        else:
            item.lucien_voice_text = self._generate_lucien_menu_text(
                item.id, item.description, user_context
            )

        return item

    async def _generate_worthiness_explanation(self, user_context: Dict[str, Any]) -> str:
        """Generate Lucien's explanation for worthiness requirements.
        
        Delegates to UserService when available for more sophisticated explanations,
        otherwise uses local implementation.
        """
        # If we have a UserService instance, delegate to it for better explanations
        if self.user_service:
            try:
                user_id = user_context.get('user_id')
                if user_id:
                    # Generate explanation via UserService
                    explanation_dict = await self.user_service.generate_worthiness_explanation(user_id)
                    if explanation_dict and 'description_text' in explanation_dict:
                        return explanation_dict['description_text']
                    elif explanation_dict and 'explanation' in explanation_dict:
                        return explanation_dict['explanation']
            except Exception as e:
                logger.warning(f"Failed to delegate worthiness explanation to UserService: {e}")
                # Fall back to local implementation
        
        # Local implementation as fallback
        worthiness_score = user_context.get('worthiness_score', 0.0)
        required_worthiness = 0.6
        relationship_level = user_context.get('relationship_level', 'formal_examiner')
        sophistication_score = user_context.get('sophistication_score', 0.0)
        diana_encounters_earned = user_context.get('diana_encounters_earned', 0)

        # Enhanced explanation based on multiple factors
        if worthiness_score < 0.2:
            return (
                f"<b>El Diván</b> representa un nivel de intimidad y comprensión que debe ganarse "
                f"a través del desarrollo personal. Sus interacciones actuales (valor: {worthiness_score:.2f}) "
                f"sugieren que está en las etapas iniciales de este viaje de sofisticación. "
                f"Continúe explorando las experiencias disponibles para construir su perfil."
            )
        elif worthiness_score < 0.4:
            return (
                f"<b>El Diván</b> está reservado para quienes han demostrado un nivel excepcional "
                f"de madurez emocional. Su progreso es notable (valor: {worthiness_score:.2f}), "
                f"pero aún requiere mayor profundidad en su comprensión. "
                f"Su relación con Lucien actualmente es '{relationship_level}' y su nivel de sofisticación es {sophistication_score:.2f}."
            )
        elif worthiness_score < 0.6:
            return (
                f"<b>El Diván</b> reconoce su crecimiento (valor: {worthiness_score:.2f}), "
                f"pero requiere la membresía VIP para completar su acceso. "
                f"Su desarrollo personal ya demuestra la sofisticación necesaria para estos privilegios. "
                f"Ha ganado {diana_encounters_earned} encuentros con Diana hasta ahora."
            )
        else:
            return (
                f"<b>✨ ¡Felicidades! ✨</b> Su perfil (valor: {worthiness_score:.2f}) "
                f"demuestra la madurez emocional y sofisticación necesarias para <b>El Diván</b>. "
                f"Su relación con Lucien es '{relationship_level}' y su nivel de sofisticación es {sophistication_score:.2f}. "
                f"Para completar su acceso, se requiere membresía VIP."
            )

    def _generate_restriction_explanation(self, item_id: str, restriction_type: str, user_context: Dict[str, Any]) -> str:
        """Generate Lucien's elegant explanation for item restrictions."""
        worthiness_score = user_context.get('worthiness_score', 0.0)
        besitos_balance = user_context.get('besitos_balance', 100)

        if restriction_type == "worthiness":
            return (
                "Ciertos tesoros requieren un nivel de sofisticación que se desarrolla "
                "naturalmente a través de sus interacciones. Su crecimiento personal "
                "determinará cuándo estos privilegios se revelan."
            )
        elif restriction_type == "besitos":
            return (
                "Este tesoro particular requiere una inversión más significativa de besitos. "
                "La paciencia y el progreso en sus misiones le proporcionarán los recursos necesarios."
            )
        elif restriction_type == "vip_membership":
            return (
                "Algunas experiencias están cuidadosamente curadas para aquellos que han "
                "elegido un compromiso más profundo con este mundo. La membresía representa "
                "una invitación a niveles de sofisticación excepcionales."
            )
        else:
            return "Este privilegio requiere desarrollo adicional en múltiples áreas."

    def _generate_store_header(self, user_context: Dict[str, Any]) -> str:
        """Generate Lucien's sophisticated store introduction."""
        worthiness_score = user_context.get('worthiness_score', 0.0)
        besitos_balance = user_context.get('besitos_balance', 100)

        return (
            f"<b>✨ Cada objeto en esta colección refleja un aspecto de la sofisticación personal. "
            f"Sus {besitos_balance} besitos y su nivel actual de development determinan "
            f"qué tesoros resonarán con su journey. ✨</b>"
        )

    def _generate_store_footer(self, user_context: Dict[str, Any]) -> str:
        """Generate Lucien's sophisticated store conclusion."""
        return (
            "<i>Recuerde: las adquisiciones más valiosas no son las que puede permitirse, "
            "sino las que ha ganado a través de su evolución personal.</i>"
        )

    def _adapt_lucien_voice_to_user(self, user_context: Dict[str, Any]) -> None:
        """Adapt Lucien's voice profile based on user characteristics."""
        try:
            user_archetype = user_context.get('user_archetype', 'explorer')
            self.lucien_profile.adapt_to_archetype(user_archetype)

            narrative_level = user_context.get('narrative_level', 0)
            has_vip = user_context.get('has_vip', False)

            if narrative_level >= 4 and has_vip:
                self.lucien_profile.user_relationship_level = RelationshipLevel.TRUSTED_CONFIDANT
            elif narrative_level >= 2:
                self.lucien_profile.user_relationship_level = RelationshipLevel.RELUCTANT_APPRECIATOR
            else:
                self.lucien_profile.user_relationship_level = RelationshipLevel.FORMAL_EXAMINER

        except Exception as e:
            logger.warning(f"Failed to adapt Lucien voice profile: {e}")

    def _generate_lucien_menu_text(self, menu_context: str, base_observation: str, user_context: Dict[str, Any]) -> str:
        """Generate Lucien's sophisticated voice text for menu items."""
        try:
            lucien_response = generate_lucien_response(
                self.lucien_profile, f"menu_access_{menu_context}", user_context
            )
            if lucien_response and lucien_response.response_text:
                return lucien_response.response_text[:200]
            return base_observation
        except Exception as e:
            logger.warning(f"Failed to generate Lucien menu text for {menu_context}: {e}")
            return base_observation

    def _generate_lucien_welcome_message(self, user_context: Dict[str, Any]) -> str:
        """Generate Lucien's sophisticated welcome message for the main menu header."""
        try:
            lucien_response = generate_lucien_response(
                self.lucien_profile, "/start", user_context
            )
            if lucien_response and lucien_response.response_text:
                return f"<b>✨ {lucien_response.response_text} ✨</b>"

            relationship_level = self.lucien_profile.user_relationship_level
            if relationship_level == RelationshipLevel.TRUSTED_CONFIDANT:
                return "<b>✨ Bienvenido a su mundo personal. Cada puerta aquí refleja su journey y sophistication excepcional ✨</b>"
            elif relationship_level == RelationshipLevel.RELUCTANT_APPRECIATOR:
                return "<b>✨ Sus opciones se expanden conforme su development progresa. Algunas posibilidades aguardan mayor sophistication ✨</b>"
            else:
                return "<b>✨ Este mundo se revela gradualmente a quienes demuestran worthiness. Cada elección será cuidadosamente evaluada ✨</b>"
        except Exception as e:
            logger.warning(f"Failed to generate Lucien welcome message: {e}")
            return "<b>✨ Bienvenido a tu mundo con Diana ✨</b>"

    def _generate_lucien_footer_message(self, user_context: Dict[str, Any]) -> str:
        """Generate Lucien's sophisticated footer message for the main menu."""
        try:
            worthiness_score = user_context.get('worthiness_score', 0.0)
            has_vip = user_context.get('has_vip', False)

            if has_vip and worthiness_score >= 0.8:
                return "<i>Sus elecciones reflejan el discernimiento y sophistication que he llegado a appreciate profundamente.</i>"
            elif worthiness_score >= 0.5:
                return "<i>Su development continúa impresionándome. Nuevas posibilidades se revelarán pronto.</i>"
            else:
                return "<i>Cada interacción contribuye a su evaluation. La paciencia y authenticity abren todas las puertas.</i>"
        except Exception as e:
            logger.warning(f"Failed to generate Lucien footer message: {e}")
            return "<i>Selecciona una opción para continuar tu journey</i>"


class NarrativeMenuBuilder(MenuBuilder):
    """Builder for narrative/Diana menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build narrative menu based on user progress."""
        try:
            user_context = self._validate_user_context(user_context)
            narrative_level = user_context.get('narrative_level', 0)
            has_vip = user_context.get('has_vip', False)
            current_fragment = user_context.get('current_fragment', 'start')
            completed_fragments = user_context.get('completed_fragments', [])
            user_id = user_context.get('user_id', 'unknown')
            parent_menu_id = kwargs.get('parent_menu_id', 'main_menu')

            logger.info(f"Building narrative menu for user {user_id} (level: {narrative_level}, vip: {has_vip})")

            items = []

            # Continuar Historia
            items.append(MenuItem(
                id="continue_story",
                text="<b>📖 Continuar Historia</b>",
                action_type=ActionType.NARRATIVE_ACTION,
                action_data=f"continue_from:{current_fragment}",
                description="Continúa donde te quedaste",
                icon="📖"
            ))

            # Los Kinkys (Niveles 1-3) - Acceso gratuito
            if narrative_level >= 1:
                items.append(MenuItem(
                    id="kinkys_level1",
                    text="<b>🌸 Los Kinkys - Nivel 1</b>",
                    action_type=ActionType.NARRATIVE_ACTION,
                    action_data="level:kinkys_1",
                    description="El Umbral del Espejo",
                    icon="🌸",
                    enabled_condition="level >= 1"
                ))

            if narrative_level >= 2:
                items.append(MenuItem(
                    id="kinkys_level2",
                    text="<b>🌸 Los Kinkys - Nivel 2</b>",
                    action_type=ActionType.NARRATIVE_ACTION,
                    action_data="level:kinkys_2",
                    description="El Regreso del Observador",
                    icon="🌸",
                    enabled_condition="level >= 2"
                ))

            if narrative_level >= 3:
                items.append(MenuItem(
                    id="kinkys_level3",
                    text="<b>🌸 Los Kinkys - Nivel 3</b>",
                    action_type=ActionType.NARRATIVE_ACTION,
                    action_data="level:kinkys_3",
                    description="El Espejo del Deseo",
                    icon="🌸",
                    enabled_condition="level >= 3"
                ))

            # El Diván (Niveles 4-6) - Requiere VIP
            if has_vip and narrative_level >= 4:
                items.append(MenuItem(
                    id="divan_level4",
                    text="<b>🛋️ El Diván - Nivel 4</b>",
                    action_type=ActionType.NARRATIVE_ACTION,
                    action_data="level:divan_4",
                    description="La Comprensión en Capas",
                    icon="🛋️",
                    required_vip=True,
                    required_level=4
                ))

            if has_vip and narrative_level >= 5:
                items.append(MenuItem(
                    id="divan_level5",
                    text="<b>🛋️ El Diván - Nivel 5</b>",
                    action_type=ActionType.NARRATIVE_ACTION,
                    action_data="level:divan_5",
                    description="La Profundización Suprema",
                    icon="🛋️",
                    required_vip=True,
                    required_level=5
                ))

            if has_vip and narrative_level >= 6:
                items.append(MenuItem(
                    id="circulo_intimo",
                    text="<b>💫 Círculo Íntimo</b>",
                    action_type=ActionType.NARRATIVE_ACTION,
                    action_data="level:circulo_intimo",
                    description="Más Allá del Final",
                    icon="💫",
                    required_vip=True,
                    required_level=6
                ))

            # Fragmentos de Memoria
            if len(completed_fragments) > 0:
                items.append(MenuItem(
                    id="memory_fragments",
                    text="<b>🧩 Fragmentos de Memoria</b>",
                    action_type=ActionType.CALLBACK,
                    action_data="show_memory_fragments",
                    description="Revive momentos especiales",
                    icon="🧩"
                ))

            # Análisis Emocional - Solo VIP
            if has_vip:
                items.append(MenuItem(
                    id="emotional_analysis",
                    text="<b>💭 Análisis Emocional</b>",
                    action_type=ActionType.CALLBACK,
                    action_data="show_emotional_analysis",
                    description="Tu perfil emocional con Diana",
                    icon="💭",
                    required_vip=True
                ))

            menu = Menu(
                menu_id="narrative_menu",
                title="🎭 Historia con Diana",
                description=f"Tu nivel actual: {narrative_level}",
                menu_type=MenuType.NARRATIVE,
                required_role=UserRole.FREE_USER,
                items=items,
                header_text="<b>🌟 Explora tu historia con Diana 🌟</b>",
                is_dynamic=True,
                parent_menu_id=parent_menu_id,
                navigation_path=kwargs.get('navigation_path', [])
            )

            self._log_menu_creation("narrative_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("narrative_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build narrative menu: {str(e)}") from e


class AdminMenuBuilder(MenuBuilder):
    """Builder for administrative menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build admin menu based on admin role."""
        try:
            user_context = self._validate_user_context(user_context)
            user_role = UserRole(user_context.get('role', 'admin'))
            user_id = user_context.get('user_id', 'unknown')
            parent_menu_id = kwargs.get('parent_menu_id', 'main_menu')

            logger.info(f"Building admin menu for user {user_id} (role: {user_role.value})")

            items = []

            # Gestión de Usuarios
            items.append(MenuItem(
                id="user_management",
                text="<b>👥 Gestión de Usuarios</b>",
                action_type=ActionType.SUBMENU,
                action_data="admin_users_menu",
                description="Administrar usuarios del sistema",
                required_role=UserRole.ADMIN
            ))

            # Gestión de Contenido Narrativo
            items.append(MenuItem(
                id="narrative_management",
                text="<b>📝 Gestión de Narrativa</b>",
                action_type=ActionType.SUBMENU,
                action_data="admin_narrative_menu",
                description="Crear y editar contenido narrativo",
                required_role=UserRole.ADMIN
            ))

            # Análisis de Comportamiento
            items.append(MenuItem(
                id="behavior_analytics",
                text="<b>📊 Análisis Comportamental</b>",
                action_type=ActionType.CALLBACK,
                action_data="show_behavior_analytics",
                description="Estadísticas de comportamiento emocional",
                required_role=UserRole.ADMIN
            ))

            # Sistema de Recompensas
            items.append(MenuItem(
                id="reward_management",
                text="<b>🎁 Gestión de Recompensas</b>",
                action_type=ActionType.SUBMENU,
                action_data="admin_rewards_menu",
                description="Configurar sistema de recompensas",
                required_role=UserRole.ADMIN
            ))

            # Configuración del Sistema
            items.append(MenuItem(
                id="system_config",
                text="<b>⚙️ Configuración</b>",
                action_type=ActionType.SUBMENU,
                action_data="admin_config_menu",
                description="Configuración del sistema",
                required_role=UserRole.ADMIN
            ))

            # Logs y Monitoreo - Solo Super Admin
            if user_role == UserRole.SUPER_ADMIN:
                items.append(MenuItem(
                    id="system_monitoring",
                    text="<b>📈 Monitoreo del Sistema</b>",
                    action_type=ActionType.CALLBACK,
                    action_data="show_system_monitoring",
                    description="Logs y métricas del sistema",
                    required_role=UserRole.SUPER_ADMIN
                ))

            # Base de Datos - Solo Super Admin
            if user_role == UserRole.SUPER_ADMIN:
                items.append(MenuItem(
                    id="database_management",
                    text="<b>🗄️ Gestión BD</b>",
                    action_type=ActionType.SUBMENU,
                    action_data="admin_database_menu",
                    description="Administración de base de datos",
                    required_role=UserRole.SUPER_ADMIN
                ))

            menu = Menu(
                menu_id="admin_menu",
                title="⚙️ Panel de Administración",
                description="Herramientas administrativas",
                menu_type=MenuType.ADMIN,
                required_role=UserRole.ADMIN,
                items=items,
                header_text="<b>🔧 Panel de Administración 🔧</b>"
            )

            self._log_menu_creation("admin_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("admin_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build admin menu: {str(e)}") from e


class MochilaMenuBuilder(MenuBuilder):
    """Builder for inventory/mochila menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build mochila/inventory menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            besitos = user_context.get('besitos', 0)
            narrative_level = user_context.get('narrative_level', 1)
            worthiness = user_context.get('worthiness', 0.0)

            items = [
                MenuItem(
                    id="ver_items", text="📦 Ver Items", action_type=ActionType.CALLBACK,
                    action_data="show_inventory_items", description="Revisa tus objetos recolectados",
                    required_role=UserRole.FREE_USER, icon="📦"
                ),
                MenuItem(
                    id="recursos", text="💰 Recursos", action_type=ActionType.CALLBACK,
                    action_data="show_resources", description=f"Besitos: {besitos}",
                    required_role=UserRole.FREE_USER, icon="💰"
                ),
                MenuItem(
                    id="progreso", text="📈 Mi Progreso", action_type=ActionType.CALLBACK,
                    action_data="show_progress", description=f"Nivel: {narrative_level}, Worthiness: {worthiness:.2f}",
                    required_role=UserRole.FREE_USER, icon="📈"
                ),
                MenuItem(
                    id="logros", text="🏅 Logros", action_type=ActionType.CALLBACK,
                    action_data="show_achievements", description="Tus logros y medallas",
                    required_role=UserRole.FREE_USER, icon="🏅"
                )
            ]

            menu = Menu(
                menu_id="mochila_menu", title="🎒 Mochila",
                description="Tu inventario personal",
                menu_type=MenuType.PROFILE, required_role=UserRole.FREE_USER, items=items,
                header_text=f"<b>🎒 Tu Inventario Personal</b>\n💋 Besitos: {besitos} | ⭐ Nivel: {narrative_level}",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("mochila_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("mochila_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build mochila menu: {str(e)}")


class MisionesMenuBuilder(MenuBuilder):
    """Builder for missions menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build missions menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')

            items = [
                MenuItem(
                    id="misiones_activas", text="📋 Misiones Activas", action_type=ActionType.CALLBACK,
                    action_data="show_active_missions", description="Misiones en curso",
                    required_role=UserRole.FREE_USER, icon="📋"
                ),
                MenuItem(
                    id="misiones_completadas", text="✅ Completadas", action_type=ActionType.CALLBACK,
                    action_data="show_completed_missions", description="Misiones terminadas",
                    required_role=UserRole.FREE_USER, icon="✅"
                ),
                MenuItem(
                    id="mision_diaria", text="📅 Misión Diaria", action_type=ActionType.CALLBACK,
                    action_data="show_daily_mission", description="Misión especial del día",
                    required_role=UserRole.FREE_USER, icon="📅"
                ),
                MenuItem(
                    id="recompensas_mision", text="🎁 Recompensas", action_type=ActionType.CALLBACK,
                    action_data="show_mission_rewards", description="Recompensas disponibles",
                    required_role=UserRole.FREE_USER, icon="🎁"
                )
            ]

            menu = Menu(
                menu_id="misiones_menu", title="🎯 Misiones",
                description="Completa misiones para ganar recompensas",
                menu_type=MenuType.GAMIFICATION, required_role=UserRole.FREE_USER, items=items,
                header_text="<b>🎯 Centro de Misiones</b>\nCompleta misiones para ganar besitos y desbloquear contenido",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("misiones_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("misiones_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build misiones menu: {str(e)}")


class TiendaMenuBuilder(MenuBuilder):
    """Builder for shop menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build shop menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            besitos = user_context.get('besitos', 0)

            items = [
                MenuItem(
                    id="items_premium", text="💎 Items Premium", action_type=ActionType.SUBMENU,
                    action_data="shop_premium_menu", description="Objetos exclusivos y especiales",
                    required_role=UserRole.FREE_USER, icon="💎"
                ),
                MenuItem(
                    id="personalizaciones", text="🎨 Personalizaciones", action_type=ActionType.SUBMENU,
                    action_data="shop_customization_menu", description="Temas y avatares",
                    required_role=UserRole.FREE_USER, icon="🎨"
                ),
                MenuItem(
                    id="potenciadores", text="⚡ Potenciadores", action_type=ActionType.SUBMENU,
                    action_data="shop_boosters_menu", description="Mejora tu experiencia",
                    required_role=UserRole.FREE_USER, icon="⚡"
                ),
                MenuItem(
                    id="paquetes_especiales", text="🎁 Paquetes Especiales", action_type=ActionType.SUBMENU,
                    action_data="shop_packages_menu", description="Ofertas combinadas",
                    required_role=UserRole.FREE_USER, icon="🎁"
                )
            ]

            menu = Menu(
                menu_id="tienda_menu", title="🏪 Tienda",
                description="Adquiere tesoros con tus besitos",
                menu_type=MenuType.STORE, required_role=UserRole.FREE_USER, items=items,
                header_text=f"<b>🏪 Tienda de Tesoros</b>\n💋 Tus Besitos: {besitos}",
                footer_text="<i>Cada compra refleja tu evolución personal</i>",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("tienda_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("tienda_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build tienda menu: {str(e)}")


class ProfileMenuBuilder(MenuBuilder):
    """Builder for VIP profile menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build VIP profile menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            has_vip = user_context.get('has_vip', False)

            if not has_vip:
                return await self._create_vip_required_menu()

            items = [
                MenuItem(
                    id="estadisticas", text="📊 Estadísticas", action_type=ActionType.CALLBACK,
                    action_data="show_detailed_stats", description="Tu perfil completo",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="📊"
                ),
                MenuItem(
                    id="personalizar", text="🎨 Personalización", action_type=ActionType.CALLBACK,
                    action_data="show_customization_options", description="Personaliza tu experiencia",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="🎨"
                ),
                MenuItem(
                    id="logros_vip", text="🏆 Logros VIP", action_type=ActionType.CALLBACK,
                    action_data="show_vip_achievements", description="Logros exclusivos VIP",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="🏆"
                ),
                MenuItem(
                    id="progreso_avanzado", text="📈 Progreso Avanzado", action_type=ActionType.CALLBACK,
                    action_data="show_advanced_progress", description="Análisis detallado de tu evolución",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="📈"
                )
            ]

            menu = Menu(
                menu_id="profile_menu", title="👤 Mi Perfil VIP",
                description="Tu perfil VIP y estadísticas",
                menu_type=MenuType.PROFILE, required_role=UserRole.FREE_USER, items=items,
                header_text="<b>👤 Mi Perfil VIP</b>\nAcceso completo a estadísticas y personalización",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("profile_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("profile_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build profile menu: {str(e)}")

    async def _create_vip_required_menu(self) -> Menu:
        """Create VIP required menu."""
        return Menu(
            menu_id="vip_required", title="🚫 Acceso VIP Requerido",
            description="Esta función requiere membresía VIP",
            menu_type=MenuType.PROFILE, required_role=UserRole.FREE_USER,
            items=[
                MenuItem(
                    id="get_vip", text="🌟 Obtener VIP", action_type=ActionType.CALLBACK,
                    action_data="show_vip_benefits", description="Descubre los beneficios VIP",
                    required_role=UserRole.FREE_USER, icon="🌟"
                )
            ],
            header_text="<b>🚫 Función VIP</b>\nEsta función está disponible solo para miembros VIP",
            parent_menu_id="main_menu"
        )


class RewardsMenuBuilder(MenuBuilder):
    """Builder for VIP rewards menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build VIP rewards menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            has_vip = user_context.get('has_vip', False)

            if not has_vip:
                return await self._create_vip_required_menu()

            items = [
                MenuItem(
                    id="recompensas_semanales", text="📅 Semanales", action_type=ActionType.CALLBACK,
                    action_data="show_weekly_rewards", description="Recompensas semanales VIP",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="📅"
                ),
                MenuItem(
                    id="boost_worthiness", text="💫 Boost Worthiness", action_type=ActionType.CALLBACK,
                    action_data="apply_worthiness_boost", description="Potencia tu worthiness",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="💫"
                ),
                MenuItem(
                    id="recompensas_exclusivas", text="✨ Exclusivas", action_type=ActionType.CALLBACK,
                    action_data="show_exclusive_rewards", description="Recompensas solo para VIP",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="✨"
                ),
                MenuItem(
                    id="historial_recompensas", text="📋 Historial", action_type=ActionType.CALLBACK,
                    action_data="show_rewards_history", description="Historial de recompensas",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="📋"
                )
            ]

            menu = Menu(
                menu_id="rewards_menu", title="🏆 Recompensas VIP",
                description="Recompensas exclusivas para miembros VIP",
                menu_type=MenuType.GAMIFICATION, required_role=UserRole.FREE_USER, items=items,
                header_text="<b>🏆 Centro de Recompensas VIP</b>\nRecompensas exclusivas para tu sophistication",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("rewards_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("rewards_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build rewards menu: {str(e)}")

    async def _create_vip_required_menu(self) -> Menu:
        """Create VIP required menu."""
        return Menu(
            menu_id="vip_required", title="🚫 Acceso VIP Requerido",
            description="Esta función requiere membresía VIP",
            menu_type=MenuType.GAMIFICATION, required_role=UserRole.FREE_USER,
            items=[
                MenuItem(
                    id="get_vip", text="🌟 Obtener VIP", action_type=ActionType.CALLBACK,
                    action_data="show_vip_benefits", description="Descubre los beneficios VIP",
                    required_role=UserRole.FREE_USER, icon="🌟"
                )
            ],
            header_text="<b>🚫 Función VIP</b>\nEsta función está disponible solo para miembros VIP",
            parent_menu_id="main_menu"
        )


class RankingMenuBuilder(MenuBuilder):
    """Builder for VIP ranking menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build VIP ranking menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            has_vip = user_context.get('has_vip', False)

            if not has_vip:
                return await self._create_vip_required_menu()

            items = [
                MenuItem(
                    id="ranking_worthiness", text="💫 Ranking Worthiness", action_type=ActionType.CALLBACK,
                    action_data="show_worthiness_ranking", description="Los más sofisticados",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="💫"
                ),
                MenuItem(
                    id="ranking_besitos", text="💋 Ranking Besitos", action_type=ActionType.CALLBACK,
                    action_data="show_besitos_ranking", description="Los más prósperos",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="💋"
                ),
                MenuItem(
                    id="mi_posicion", text="📍 Mi Posición", action_type=ActionType.CALLBACK,
                    action_data="show_my_ranking_position", description="Tu posición actual",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="📍"
                ),
                MenuItem(
                    id="competencias", text="🏆 Competencias", action_type=ActionType.CALLBACK,
                    action_data="show_competitions", description="Competencias activas",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="🏆"
                )
            ]

            menu = Menu(
                menu_id="ranking_menu", title="📊 Ranking VIP",
                description="Compite con otros usuarios VIP",
                menu_type=MenuType.GAMIFICATION, required_role=UserRole.FREE_USER, items=items,
                header_text="<b>📊 Ranking de Sophistication</b>\nCompite con los usuarios más distinguidos",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("ranking_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("ranking_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build ranking menu: {str(e)}")

    async def _create_vip_required_menu(self) -> Menu:
        """Create VIP required menu."""
        return Menu(
            menu_id="vip_required", title="🚫 Acceso VIP Requerido",
            description="Esta función requiere membresía VIP",
            menu_type=MenuType.GAMIFICATION, required_role=UserRole.FREE_USER,
            items=[
                MenuItem(
                    id="get_vip", text="🌟 Obtener VIP", action_type=ActionType.CALLBACK,
                    action_data="show_vip_benefits", description="Descubre los beneficios VIP",
                    required_role=UserRole.FREE_USER, icon="🌟"
                )
            ],
            header_text="<b>🚫 Función VIP</b>\nEsta función está disponible solo para miembros VIP",
            parent_menu_id="main_menu"
        )


class AuctionsMenuBuilder(MenuBuilder):
    """Builder for VIP auctions menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build VIP auctions menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            has_vip = user_context.get('has_vip', False)
            besitos = user_context.get('besitos', 0)

            if not has_vip:
                return await self._create_vip_required_menu()

            items = [
                MenuItem(
                    id="subastas_activas", text="🔥 Activas", action_type=ActionType.CALLBACK,
                    action_data="show_active_auctions", description="Subastas en curso",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="🔥"
                ),
                MenuItem(
                    id="mis_pujas", text="💰 Mis Pujas", action_type=ActionType.CALLBACK,
                    action_data="show_my_bids", description="Tus pujas actuales",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="💰"
                ),
                MenuItem(
                    id="subastas_ganadas", text="🏆 Ganadas", action_type=ActionType.CALLBACK,
                    action_data="show_won_auctions", description="Subastas que has ganado",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="🏆"
                ),
                MenuItem(
                    id="historial_subastas", text="📋 Historial", action_type=ActionType.CALLBACK,
                    action_data="show_auction_history", description="Historial completo",
                    required_role=UserRole.FREE_USER, required_vip=True, icon="📋"
                )
            ]

            menu = Menu(
                menu_id="auctions_menu", title="💎 Subastas VIP",
                description="Participa en subastas exclusivas",
                menu_type=MenuType.GAMIFICATION, required_role=UserRole.FREE_USER, items=items,
                header_text=f"<b>💎 Casa de Subastas VIP</b>\n💋 Tus Besitos: {besitos}",
                footer_text="<i>Solo los tesoros más exclusivos llegan aquí</i>",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("auctions_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("auctions_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build auctions menu: {str(e)}")

    async def _create_vip_required_menu(self) -> Menu:
        """Create VIP required menu."""
        return Menu(
            menu_id="vip_required", title="🚫 Acceso VIP Requerido",
            description="Esta función requiere membresía VIP",
            menu_type=MenuType.GAMIFICATION, required_role=UserRole.FREE_USER,
            items=[
                MenuItem(
                    id="get_vip", text="🌟 Obtener VIP", action_type=ActionType.CALLBACK,
                    action_data="show_vip_benefits", description="Descubre los beneficios VIP",
                    required_role=UserRole.FREE_USER, icon="🌟"
                )
            ],
            header_text="<b>🚫 Función VIP</b>\nEsta función está disponible solo para miembros VIP",
            parent_menu_id="main_menu"
        )


class DivanMenuBuilder(MenuBuilder):
    """Builder for VIP Diván menu system."""

    async def build_menu(self, user_context: Dict[str, Any], **kwargs) -> Menu:
        """Build VIP Diván menu."""
        try:
            user_context = self._validate_user_context(user_context)
            user_id = user_context.get('user_id', 'unknown')
            has_vip = user_context.get('has_vip', False)
            worthiness = user_context.get('worthiness', 0.0)

            if not has_vip or worthiness < 7.0:
                return await self._create_divan_access_denied_menu(has_vip, worthiness)

            items = [
                MenuItem(
                    id="conversacion_intima", text="💬 Conversación Íntima", action_type=ActionType.CALLBACK,
                    action_data="start_intimate_conversation", description="Diálogo profundo con Lucien",
                    required_role=UserRole.FREE_USER, required_vip=True, required_worthiness=7.0, icon="💬"
                ),
                MenuItem(
                    id="experiencias_personalizadas", text="🎨 Experiencias Personalizadas", action_type=ActionType.SUBMENU,
                    action_data="divan_experiences_menu", description="Experiencias únicas para tu sophistication",
                    required_role=UserRole.FREE_USER, required_vip=True, required_worthiness=7.0, icon="🎨"
                ),
                MenuItem(
                    id="biblioteca_secreta", text="📚 Biblioteca Secreta", action_type=ActionType.CALLBACK,
                    action_data="access_secret_library", description="Conocimientos reservados",
                    required_role=UserRole.FREE_USER, required_vip=True, required_worthiness=7.0, icon="📚"
                ),
                MenuItem(
                    id="evaluacion_detallada", text="📊 Evaluación Detallada", action_type=ActionType.CALLBACK,
                    action_data="detailed_worthiness_evaluation", description="Análisis completo de tu sophistication",
                    required_role=UserRole.FREE_USER, required_vip=True, required_worthiness=7.0, icon="📊"
                )
            ]

            menu = Menu(
                menu_id="divan_menu", title="🛋️ Mi Diván",
                description="Tu espacio íntimo de comprensión profunda",
                menu_type=MenuType.VIP, required_role=UserRole.FREE_USER, items=items,
                header_text=f"<b>🛋️ El Diván de la Sophistication</b>\nWorthiness: {worthiness:.2f}/10.0",
                footer_text="<i>Un privilegio ganado a través de la evolución personal</i>",
                parent_menu_id="main_menu"
            )

            self._log_menu_creation("divan_menu", user_id, True)
            return menu

        except Exception as e:
            self._log_menu_creation("divan_menu", user_context.get('user_id', 'unknown'), False, str(e))
            raise MenuGenerationError(f"Failed to build divan menu: {str(e)}")

    async def _create_divan_access_denied_menu(self, has_vip: bool, worthiness: float) -> Menu:
        """Create access denied menu for Diván."""
        if not has_vip:
            message = "El Diván requiere membresía VIP y worthiness excepcional"
            items = [
                MenuItem(
                    id="get_vip", text="🌟 Obtener VIP", action_type=ActionType.CALLBACK,
                    action_data="show_vip_benefits", description="Primer paso hacia el Diván",
                    required_role=UserRole.FREE_USER, icon="🌟"
                )
            ]
        else:
            message = f"Worthiness insuficiente: {worthiness:.2f}/7.0"
            items = [
                MenuItem(
                    id="improve_worthiness", text="📈 Mejorar Worthiness", action_type=ActionType.CALLBACK,
                    action_data="worthiness_improvement_guide", description="Guía para elevar tu sophistication",
                    required_role=UserRole.FREE_USER, icon="📈"
                )
            ]

        return Menu(
            menu_id="divan_access_denied", title="🚫 Acceso al Diván Denegado",
            description=message,
            menu_type=MenuType.VIP, required_role=UserRole.FREE_USER, items=items,
            header_text=f"<b>🚫 {message}</b>",
            parent_menu_id="main_menu"
        )


class VIPMenuBuilder(MenuBuilder):
    """Builder for VIP exclusive menu system."""

    async def build_menu(self, user_context: Dict[str, Any]) -> Menu:
        """Build VIP menu with exclusive content."""
        narrative_level = user_context.get('narrative_level', 0)

        items = []

        # Acceso al Diván
        items.append(MenuItem(
            id="divan_exclusive",
            text="<b>🛋️ El Diván Privado</b>",
            action_type=ActionType.NARRATIVE_ACTION,
            action_data="divan:private_access",
            description="Tu espacio íntimo con Diana",
            required_vip=True
        ))

        # Archivo Personal de Diana
        items.append(MenuItem(
            id="diana_personal_archive",
            text="<b>📚 Archivo Personal de Diana</b>",
            action_type=ActionType.CALLBACK,
            action_data="show_diana_archive",
            description="Memorias íntimas y reflexiones",
            required_vip=True,
            required_level=4
        ))

        # Diario Íntimo
        if narrative_level >= 5:
            items.append(MenuItem(
                id="diana_intimate_diary",
                text="<b>📖 Diario Íntimo de Diana</b>",
                action_type=ActionType.CALLBACK,
                action_data="show_intimate_diary",
                description="Pensamientos más profundos",
                required_vip=True,
                required_level=5
            ))

        # Contenido Exclusivo
        items.append(MenuItem(
            id="exclusive_content",
            text="<b>✨ Contenido Exclusivo</b>",
            action_type=ActionType.SUBMENU,
            action_data="vip_exclusive_menu",
            description="Solo para miembros VIP",
            required_vip=True
        ))

        # Sesiones Personalizadas
        items.append(MenuItem(
            id="personalized_sessions",
            text="<b>💫 Sesiones Personalizadas</b>",
            action_type=ActionType.CALLBACK,
            action_data="start_personalized_session",
            description="Experiencias adaptadas a ti",
            required_vip=True
        ))

        return Menu(
            menu_id="vip_menu",
            title="💎 Área VIP",
            description="Contenido exclusivo para miembros VIP",
            menu_type=MenuType.VIP,
            required_role=UserRole.VIP_USER,
            items=items,
            header_text="<b>💎 Bienvenido al Área VIP 💎</b>",
            footer_text="<i>Contenido exclusivo diseñado para ti</i>"
        )


class MenuValidationUtils:
    """Utility class for menu validation and optimization."""

    @staticmethod
    def validate_callback_data_length(data: str) -> bool:
        """Check if callback data is within Telegram limits."""
        return len(data.encode('utf-8')) <= TELEGRAM_CALLBACK_DATA_MAX_LENGTH

    @staticmethod
    def optimize_menu_hierarchy(menu: Menu, max_depth: int = 3) -> Menu:
        """Optimize menu hierarchy to reduce navigation depth."""
        if len(menu.navigation_path) > max_depth:
            # Flatten submenu items if hierarchy is too deep
            flattened_items = []
            for item in menu.items:
                if item.action_type == ActionType.SUBMENU and item.submenu_items:
                    # Convert submenu items to regular items with prefixed names
                    for subitem in item.submenu_items:
                        flattened_item = MenuItem(
                            id=f"{item.id}_{subitem.id}",
                            text=f"{item.icon} {subitem.text}",
                            action_type=subitem.action_type,
                            action_data=subitem.action_data,
                            description=f"{item.text}: {subitem.description}",
                            required_role=subitem.required_role,
                            required_vip=subitem.required_vip,
                            required_level=subitem.required_level
                        )
                        flattened_items.append(flattened_item)
                else:
                    flattened_items.append(item)

            menu.items = flattened_items
            logger.info(f"Flattened menu hierarchy for '{menu.menu_id}' - reduced depth")

        return menu

    @staticmethod
    def add_performance_metadata(menu: Menu) -> Menu:
        """Add performance metadata to menu for analytics."""
        menu.metadata = menu.metadata or {}
        menu.metadata.update({
            'created_at': datetime.now().isoformat(),
            'item_count': len(menu.items),
            'has_vip_items': any(item.required_vip for item in menu.items),
            'max_role_required': max((item.required_role for item in menu.items), default=UserRole.FREE_USER, key=lambda x: x.value)
        })
        return menu


from src.utils.cache_manager import cache_manager



class MenuFactory:
    """Main factory class for generating menus based on context."""

    def __init__(self, user_service: Optional[UserService] = None):
        """Initialize menu factory with builders.
        
        Args:
            user_service (Optional[UserService]): UserService instance for delegation of complex operations
        """
        self.user_service = user_service
        self.builders = {
            MenuType.MAIN: MainMenuBuilder(user_service),
            MenuType.NARRATIVE: NarrativeMenuBuilder(),
            MenuType.ADMIN: AdminMenuBuilder(),
            MenuType.VIP: VIPMenuBuilder(),
            MenuType.STORE: TiendaMenuBuilder(),
            MenuType.GAMIFICATION: MisionesMenuBuilder(),
            MenuType.PROFILE: ProfileMenuBuilder(),
            MenuType.EMOTIONAL: MainMenuBuilder(user_service),
            MenuType.DIANA: MainMenuBuilder(user_service),
            MenuType.SETTINGS: MainMenuBuilder(user_service),
            MenuType.HELP: MainMenuBuilder(user_service)
        }

        # Additional specific menu builders
        self.specific_builders = {
            "mochila_menu": MochilaMenuBuilder(),
            "misiones_menu": MisionesMenuBuilder(),
            "tienda_menu": TiendaMenuBuilder(),
            "profile_menu": ProfileMenuBuilder(),
            "rewards_menu": RewardsMenuBuilder(),
            "ranking_menu": RankingMenuBuilder(),
            "auctions_menu": AuctionsMenuBuilder(),
            "divan_menu": DivanMenuBuilder()
        }

        self.menu_definitions = self._initialize_menu_definitions()
        self.cache_manager = cache_manager
        # Initialize cache connection only when running in async context
        # Use a flag to track if we're connected to avoid multiple connection attempts
        self._cache_connected = False
        # Callback data mapping for compression
        self.callback_mapping = {}
        logger.info("MenuFactory initialized (cache connection will be established on first use)")

    def _initialize_menu_definitions(self) -> Dict[str, Dict]:
        """Initialize static menu definitions for organic menu system."""
        # Use centralized menu definitions
        return menu_system_config.definitions

    async def create_menu(self, menu_type: Union[MenuType, str], user_context: Dict[str, Any], **kwargs) -> Menu:
        """Create menu based on type and user context, with caching."""
        # Try to use cache if available and connected
        try:
            if not self._cache_connected:
                await self.cache_manager.connect()
                self._cache_connected = True
                logger.info("Cache manager connected successfully")
            
            # Convert string menu_type to MenuType enum if needed
            if isinstance(menu_type, str):
                try:
                    menu_type = MenuType(menu_type)
                except ValueError:
                    logger.warning(f"Invalid menu type '{menu_type}', defaulting to MAIN")
                    menu_type = MenuType.MAIN
            
            cached_menu = await self.cache_manager.get_menu(menu_type.value, user_context)
            if cached_menu:
                return cached_menu
        except Exception as e:
            logger.warning(f"Cache operation failed, proceeding without cache: {str(e)}")
            # Continue without cache if there's an error

        # Build the menu
        if menu_type in self.builders:
            new_menu = await self.builders[menu_type].build_menu(user_context, **kwargs)
        else:
            # Try to get from centralized definitions
            menu_config = menu_system_config.get_menu_definition(menu_type.value)
            if menu_config:
                new_menu = Menu.from_config(menu_config, user_context)
            else:
                new_menu = self._create_basic_menu(menu_type, user_context)

        # Try to cache the new menu
        try:
            if self._cache_connected:
                await self.cache_manager.set_menu(new_menu, user_context)
        except Exception as e:
            logger.warning(f"Failed to cache menu: {str(e)}")
            
        return new_menu

    async def create_organic_store_menu(self, user_context: Dict[str, Any]) -> Menu:
        """Create organic unified store menu."""
        main_builder = self.builders[MenuType.STORE]
        if hasattr(main_builder, 'build_organic_store_menu'):
            return main_builder.build_organic_store_menu(user_context)
        else:
            return await self.create_menu(MenuType.STORE, user_context)

    async def create_menu_by_id(self, menu_id: str, user_context: Dict[str, Any]) -> Optional[Menu]:
        """Create menu by specific ID using the appropriate builder."""
        # Check specific builders first
        if menu_id in self.specific_builders:
            return await self.specific_builders[menu_id].build_menu(user_context)

        # Check menu definitions
        if menu_id in self.menu_definitions:
            return self._create_organic_menu_from_definition(menu_id, user_context)

        # Special cases
        elif menu_id == "organic_store_menu":
            main_builder = self.builders[MenuType.STORE]
            if hasattr(main_builder, 'build_organic_store_menu'):
                return main_builder.build_organic_store_menu(user_context)
            else:
                return await main_builder.build_menu(user_context)

        return None

    def _create_organic_menu_from_definition(self, menu_id: str, user_context: Dict[str, Any]) -> Menu:
        """Create menu from static definition using organic principles."""
        definition = self.menu_definitions.get(menu_id)
        if not definition:
            # Fallback to basic menu
            return self._create_basic_menu(MenuType.MAIN, user_context)
            
        main_builder = self.builders[MenuType.MAIN]  # Use main builder

        items = []
        for item_def in definition.get("items", []):
            # Always show items, but process restrictions organically
            item = MenuItem(
                id=item_def.get("id", ""),
                text=item_def.get("text", ""),
                action_type=ActionType(item_def.get("action_type", ActionType.CALLBACK)),
                action_data=item_def.get("action", item_def.get("action_data", "")),
                description=item_def.get("description", ""),
                required_role=UserRole(item_def.get("required_role", "free_user")),
                required_vip=item_def.get("required_vip", False),
                required_level=item_def.get("required_level", 0),
                requires_besitos=item_def.get("requires_besitos", 0),
                required_worthiness=item_def.get("required_worthiness", 0.0)
            )

            # Process with organic restrictions
            if hasattr(main_builder, '_process_store_item'):
                item = main_builder._process_store_item(item, user_context)

            items.append(item)

        return Menu(
            menu_id=menu_id,
            title=definition.get("title", "Menú"),
            description=definition.get("description", "Cada opción refleja tu journey personal"),
            menu_type=MenuType(definition.get("menu_type", "profile")),
            required_role=UserRole(definition.get("required_role", "free_user")),
            items=items,
            header_text=definition.get("header_text", ""),
            footer_text=definition.get("footer_text", ""),
            max_columns=definition.get("max_columns", 2),
            is_dynamic=definition.get("is_dynamic", False),
            parent_menu_id=definition.get("parent_menu_id", "main_menu"),
            navigation_path=definition.get("navigation_path", [])
        )

    def _user_meets_organic_requirements(self, item_def: Dict, user_context: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
        """Check if user meets requirements using organic system (always visible, elegant restrictions)."""
        # In organic system, everything is visible but elegantly restricted
        restriction_reason = None

        required_vip = item_def.get("required_vip", False)
        has_vip = user_context.get("has_vip", False)

        required_worthiness = item_def.get("required_worthiness", 0.0)
        user_worthiness = user_context.get("worthiness_score", 0.0)

        if required_vip and not has_vip:
            restriction_reason = "vip_membership"
        elif required_worthiness > user_worthiness:
            restriction_reason = "worthiness"

        return True, restriction_reason  # Always visible, restriction noted

    def _role_has_access(self, user_role: UserRole, required_role: UserRole) -> bool:
        """Check if user role has access to required role."""
        role_hierarchy = {
            UserRole.GUEST: 0,
            UserRole.FREE_USER: 1,
            UserRole.VIP_USER: 2,
            UserRole.ADMIN: 3,
            UserRole.SUPER_ADMIN: 4
        }

        return role_hierarchy[user_role] >= role_hierarchy[required_role]

    def _create_basic_menu(self, menu_type: MenuType, user_context: Dict[str, Any]) -> Menu:
        """Create basic fallback menu."""
        return Menu(
            menu_id="basic_menu",
            title="📋 Menú Básico",
            description="Menú básico del sistema",
            menu_type=menu_type,
            required_role=UserRole.FREE_USER,
            items=[
                MenuItem(
                    id="back_to_main",
                    text="<b>🔙 Volver al Menú Principal</b>",
                    action_type=ActionType.CALLBACK,
                    action_data="main_menu",
                    description="Regresar al menú principal"
                )
            ]
        )


# Global menu factory instance
menu_factory = MenuFactory()


async def get_menu_for_user(menu_type: Union[MenuType, str], user_context: Dict[str, Any]) -> Menu:
    """Convenience function to get menu for user."""
    if isinstance(menu_type, str):
        menu = menu_factory.create_menu_by_id(menu_type, user_context)
        if menu:
            return menu

        try:
            menu_type = MenuType(menu_type)
        except ValueError:
            menu_type = MenuType.MAIN

    return await menu_factory.create_menu(menu_type, user_context)
